# Generated by Django 2.1.7 on 2019-06-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
