# Generated by Django 2.1.7 on 2019-06-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allowed_users',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
