# Generated by Django 2.1.7 on 2019-06-08 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_submitted'),
        ('game', '0003_game_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='game',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='game',
            name='allowed_users',
            field=models.ManyToManyField(to='users.Users'),
        ),
    ]
